name: 'Check for a changeset'
description: 'Fail if no .changeset/*.md file is included in the PR.'
inputs:
  exclude:
    description: list of comma-separated paths (files or directories ending in /) that don't need a changeset when changed. Default .github/
    required: false
    default: .github/
  exclude_extensions:
    description: a list of comma-separated extensions that don't need a changeset when changed. Default <empty>
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: ./actions/get-changed-files
      id: changed

    - uses: ./actions/filter-files
      id: match
      with:
        changed-files: ${{ steps.changed.outputs.files }}
        invert: true
        files: ${{ inputs.exclude }}
        extensions: $${{ inputs.exclude_extensions }}
        file_globs: ${{ inputs.exclude_glob }}

    - uses: actions/github-script@v6
      with:
        script: |
          const inputFiles = JSON.parse(`${{ steps.match.outputs.filtered }}`);
          require('./actions/check-for-changeset/index.js')({context, core, inputFiles})
