name: 'Check for a changeset'
description: 'Fail if no .changeset/*.md file is included in the PR.'
runs:
  using: "composite"
  steps:
    - uses: Khan/actions@get-changed-files-v1
      id: changed
    - uses: actions/github-script@v6
      with:
        script: |
          const inputFiles = JSON.parse(`${{ steps.changed.outputs.files }}`);
          require('./actions/check-for-changeset/index.js')({context, core, inputFiles})
