name: Setup Keeper
description: Install keeper & set up authentication
inputs:
  config:
    description: contents of the keeper config file
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10.6"
    - name: install keepercommander
      shell: bash
      run: |
        python3 -m pip install --upgrade pip==22.2.2
        python3 -m pip install cryptography==38.0.4 pyOpenSSL==22.1.0 keepercommander==16.8.3
        echo "$PATH"
        echo "$HOME"
        python3 -m site --user-base
        mkdir /Users/runner/.keeper

    - uses: actions/github-script@v6
      with:
        script: const config = `${{ inputs.config }}`;
          require('fs').writeFileSync('/Users/runner/.keeper/config.json', config)

    - name: Check that keeper is installed correctly
      shell: bash
      run: |
        keeper this-device
        keeper whoami
