name: Setup Keeper
description: Install keeper & set up authentication
inputs:
  config:
    description: contents of the keeper config file
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10.6"
    - name: install keepercommander
      shell: bash
      run: |
        python3 --version
        python --version
        pip3 -V
        python3 -m pip -V
        which pip
        which python3
        python3 -m pip install --upgrade pip==22.2.2
        python3 -m pip -V
        python3 -m pip install cryptography==38.0.4 pyOpenSSL==22.1.0 keepercommander==16.8.3
        echo "$PATH"
        python3 -m site --user-base

    - uses: actions/github-script@v6
      with:
        script: const config = `${{ inputs.config }}`;
          require('fs').writeFileSync('./.keeper-config.json', config)

    - name: Set up the keeper config file
      shell: bash
      run: echo "KEEPER_CONFIG_FILE=$HOME/.keeper-config.json" >> $GITHUB_ENV

    - name: Check that keeper is installed correctly
      shell: bash
      run: |
        keeper this-device
        keeper whoami
