name: Setup Keeper
description: Install keeper & set up authentication
inputs:
  config:
    description: contents of the keeper config file
    required: true
runs:
  using: "composite"
  steps:
    - name: install keepercommander
      shell: bash
      run: |
        brew install pyenv
        echo "export PATH=\"`pyenv init --path`/bin:\$PATH\"" >> ~/.bashrc
        echo 'eval "$(pyenv init --path)"' >> ~/.bash_profile
        source ~/.bashrc
        eval "$(pyenv init -)"
        pyenv install 3.10.8
        pyenv local 3.10.8
        pyenv global 3.10.8
        pyenv shell 3.10.8
        python3 --version
        python --version
        pip3 -V
        python3 -m pip3
        which pip
        which python3
        pyenv versions
        pyenv which pip
        pyenv which python
        echo "export PATH=\"`python3 -m site --user-base`/bin:\$PATH\"" >> ~/.bashrc
        source ~/.bashrc
        python3 -m pip install cryptography==37.0.2 pyOpenSSL==22.0.0 keepercommander==16.6.5
        echo "$PATH"
        python3 -m site --user-base

    - uses: actions/github-script@v6
      with:
        script: const config = `${{ inputs.config }}`;
          require('fs').writeFileSync('./.keeper-config.json', config)

    - name: Set up the keeper config file
      shell: bash
      run: echo "KEEPER_CONFIG_FILE=$HOME/.keeper-config.json" >> $GITHUB_ENV

    - name: Check that keeper is installed correctly
      shell: bash
      run: |
        keeper this-device
        keeper whoami
