name: Setup Keeper
description: Install keeper & set up authentication
inputs:
  config:
    description: contents of the keeper config file
    required: true
runs:
  using: "composite"
  steps:
    - name: install keepercommander
      shell: bash
      run: pip3 install wheel cryptography==37.0.2 pyOpenSSL==22.0.0 keepercommander==16.6.5 --use-pep517

    - uses: actions/github-script@v6
      with:
        script: const config = `${{ inputs.config }}`;
          require('fs').writeFileSync('./.keeper-config.json', config)

    - name: Set up the keeper config file
      shell: bash
      run: echo "KEEPER_CONFIG_FILE=$HOME/.keeper-config.json" >> $GITHUB_ENV

    - name: Check that keeper is installed correctly
      shell: bash
      run: |
        keeper this-device
        keeper whoami
