name: 'Shared Node Cache'
description: 'Install & cache our npm dependencies (using pnpm)'
inputs:
  node-version:
    description: 'Node version to use'
    required: false
    default: '20.x'
  ssh-private-key:
    description: 'A private SSH key so that we can obtain private dependencies like our event schema package'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    # Set up SSH key so that the install step can install packages from private
    # git repos.
    - uses: webfactory/ssh-agent@v0.9.0
      if: ${{ inputs.ssh-private-key != '' }}
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    # Now install node_modules (we cache the pnpm store above)
    - name: pnpm install
      shell: sh
      run: pnpm install ---frozen-lockfile
