name: Setup Keeper
description: Install keeper & set up authentication
inputs:
  config:
    description: contents of the keeper config file
    required: true
runs:
  using: "composite"
  steps:
    - name: install keepercommander
      shell: bash
      run: |
        pip3 install cryptography==37.0.2 pyOpenSSL==22.0.0 keepercommander==16.6.5
        echo "$HOME"
        echo "$PATH"
        echo "export PATH=\"`python3 -m site --user-base`/bin:\$PATH\"" >> ~/.bashrc
        source ~/.bashrc
        echo "$PATH"
        which keeper
        pip3 show -f keepercommander

    - uses: actions/github-script@v6
      with:
        script: const config = `${{ inputs.config }}`;
          require('fs').writeFileSync('./config.json', config)

    - name: Set up the keeper config file
      shell: bash
      run: echo "KEEPER_CONFIG_FILE=$HOME/config.json" >> $GITHUB_ENV

    - name: Check that keeper is installed correctly
      shell: bash
      run: |
        keeper shell --config ./config.json
        keeper this-device
        keeper whoami
