name: 'Check for a changeset'
description: 'Fail if no .changeset/*.md file is included in the PR.'
inputs:
  exclude:
    description: list of comma-separated paths (files or directories ending in /) that don't need a changeset when changed. Default .github/
    required: false
    default: .github/

runs:
  using: "composite"
  steps:
    - uses: Khan/actions@get-changed-files-v1.1.0
      id: changed

    - uses: Khan/actions@filter-files-v0.2.0
      id: match
      with:
        changed-files: ${{ steps.changed.outputs.files }}
        invert: true
        files: ${{ inputs.exclude }}

    - uses: actions/github-script@v6
      with:
        script: |
          const inputFiles = JSON.parse(`${{ steps.match.outputs.filtered }}`);
          require('${{ github.action_path }}/index.js')({context, core, inputFiles})
