name: "Setup"
description: "Install pnpm, Node.js, and the workspace's node modules"

runs:
    using: "composite"
    steps:
        - name: Install pnpm
          uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
          with:
              run_install: false

        - name: Use Node.js 24.x
          uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
          with:
              node-version: "24.x"
              cache: "pnpm"

        - name: Install dependencies
          shell: bash
          run: pnpm install --frozen-lockfile

        - name: Report outdated dependencies
          uses: dev-infra-tools/pnpm-outdated-annotate@v2
          with:
              fail-on: none
