name: Validate Workflows and Actions

on:
    pull_request:
        paths:
            - ".github/**/*.yml"
            - ".github/**/*.yaml"

jobs:
    validate-workflows:
        timeout-minutes: 15
        # Set the org var or repo var USE_GITHUB_RUNNERS to 'true'
        # to use github-hosted runners instead of ephemeral runners
        # without needing to deploy workflow changes.
        runs-on: "${{ vars.USE_GITHUB_RUNNERS == 'true' && 'ubuntu-latest' || 'ephemeral-runner' }}"
        # pull-requests & issues write permissions are required to post comments.
        permissions:
            contents: write
            pull-requests: write
            issues: write
            packages: read
        steps:
            # We need to use the bot token here to be able to push fixes back.
            # We also need to explicitly set the ref to ensure we are checking
            # out the correct branch. See:
            # https://github.com/EndBug/add-and-commit?tab=readme-ov-file#working-with-prs
            - name: Checking out latest commit
              uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
                  token: ${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}

            - name: Setup
              uses: ./.github/actions/setup
              with:
                  ssh-key: ${{ secrets.KHAN_ACTIONS_BOT_SSH_PRIVATE_KEY }}
              timeout-minutes: 5

            - name: Fix checkout-followed-by-setup
              uses: ./.github/actions/run-and-commit
              with:
                  working-directory: ./
                  run: pnpm fix-workflows

            - name: Format with Prettier
              uses: ./.github/actions/run-and-commit
              with:
                  working-directory: ./
                  run: pnpm prettier --write ".github/**/*.yml"

            - name: Push Autofixes
              shell: bash
              run: git push

            - name: Run Actionlint
              shell: bash
              run: |
                  echo "::add-matcher::.github/actionlint-matcher.json"
                  bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/03d0035246f3e81f36aed592ffb4bebf33a03106/scripts/download-actionlint.bash) 1.7.7
                  ./actionlint -color .github/workflows/*.yml
