name: Setup Keeper
description: Install keeper & set up authentication
inputs:
  config:
    description: contents of the keeper config file
    required: true
runs:
  using: "composite"
  steps:
    - name: install keepercommander
      shell: bash
      run: pip3 install cryptography==37.0.2 pyOpenSSL==22.0.0 keepercommander==16.6.5

    - name: Set up the keeper config file
      shell: bash
      run: |
        cat << EOF > $HOME/.keeper-config.json
        ${{ inputs.config }}
        EOF
        echo "KEEPER_CONFIG_FILE=$HOME/.keeper-config.json" >> $GITHUB_ENV

    - name: Check that keeper is installed correctly
      shell: bash
      run: |
        keeper this-device
        keeper whoami
