name: Setup Keeper
description: Install keeper & set up authentication
inputs:
  config:
    description: contents of the keeper config file
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10.6"
    - name: install keepercommander
      shell: bash
      run: |
        python3 -m pip install --upgrade pip==22.2.2
        python3 -m pip install cryptography==37.0.2 pyOpenSSL==22.0.0 keepercommander==16.7.10

    - uses: actions/github-script@v6
      with:
        script: const config = `${{ inputs.config }}`;
          require('fs').writeFileSync(process.env.HOME + '/.keeper-config.json', config)

    - name: Set up the keeper config file
      shell: bash
      run: echo "KEEPER_CONFIG_FILE=$HOME/.keeper-config.json" >> $GITHUB_ENV

    - name: Check that keeper is installed correctly
      shell: bash
      run: keeper this-device