name: Gerald - Notify and Request Reviewers On Pull Request
'on':
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]

jobs:
  gerald:
    if: "github.event.action != 'edited' || github.event.changes.body.from != ''"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/gerald-pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          admin-token: ${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}
