name: Gerald - Notify and Request Reviewers On Pull Request
'on':
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]

jobs:
  gerald:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: console.log(JSON.stringify(context.payload))
      - uses: actions/checkout@v2
      - uses: ./actions/gerald-pr
        name: Run Gerald Thanks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          admin-token: ${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}
