name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # necessary for publishing releases and pushing tags
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./actions/shared-node-cache

      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        id: has-changesets
        with:
          script: |
            return require('fs')
              .readdirSync('.changeset')
              .some(x => x !== 'README.md' && !x.startsWith('.') && x.endsWith('.md'))
          result-encoding: json

      - run: pnpm run build
      - run: node -r @swc-node/register utils/run-publish.ts
        if: steps.has-changesets.outputs.result == 'false'

      - name: Create Release Pull Request or Publish as tags
        if: steps.has-changesets.outputs.result == 'true'
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1
        with:
          publish: exit 1
        env:
          GITHUB_TOKEN: ${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}
          # We don't specify NPM_TOKEN here because we don't publish to npm. We
          # only use the changesets action to prepare the Version Packages PR,
          # but once we land that, we use our publish-to-github-tags approach
          # which is implemented above in the utils/run-publish.ts step.
